version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

formatters:
  enable:
    - gofmt
